import type { Metadata } from "next";
import "./globals.css";


import Menu from '@/components/Menu'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex bg-background text-foreground">
        <Menu />
        <main className="flex-1 min-h-screen">{children}</main>
      </body>
    </html>
  );
}
